version:  '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        ports:
            - "7861:7861"
            - "7860:7860"
